project_id = "sxzrzkgodbounjvrjcuj"

[functions.analyze-medical-doc]
verify_jwt = false

[functions.pet-chat]
verify_jwt = false

[functions.check-notifications]
verify_jwt = false

[functions.complete-onboarding]
verify_jwt = false

[functions.save-onboarding]
verify_jwt = false
